### ISSUE TITLE
/setup does not work

### ISSUE THREAD

**Issue by mfehr94** [CardinalHorizon/VAOS#2]
If I run /setup nothing happens. Blank white page. I'm pretty sure I'm doing something wrong.
If I do it the 'Dedicated Servers (SSH Access)' Way it works perfect.

**Comment by BossOfGames** [comment]
It seems the installer was not properly pushed up to the repo along with the controller not doing what it's supposed to.

````php
public function index(Request $request)
    {
        // Return the view right now
        if ($request->query('fresh')
            return view('install.fresh');
        else
            return view('install.start');
    }
````
That's what it's supposed to do. Instead, it is blank.

**Comment by mfehr94** [comment]
![runmigration_method](https://cloud.githubusercontent.com/assets/14167832/22173960/b2275a8c-dfd1-11e6-9610-60e06d2b87af.PNG)

Method is missing

**Comment by mfehr94** [comment]
I have changed the method name and made changes in the method so that auto login and the redirection work.
