### ISSUE TITLE
Install looks incomplete

### ISSUE THREAD

**Issue by gugaua** [CardinalHorizon/VAOS#5]
I am not sure if my installation is working fine

http://vaos.gugaua.at/

It seems like a simple index.html/php site is missing.

I am using php7 mysql 5.5 and apache 2.4 is that okay?

**Comment by mfehr94** [comment]
No everything is ok your domain has to point to the public folder. There are 2 ways to do that.
1. If you can change it in your Hostingdashboard.
2. create a .htaccess file with the following content:
`<IfModule mod_rewrite.c>
    RewriteEngine On

    RewriteRule ^(.*)$ public/$1 [L]
</IfModule>`

**Comment by BossOfGames** [comment]
Whoops. Forgot to mention to point it to public in the install instructions. I will change that.
