### ISSUE TITLE
login not working

### ISSUE THREAD

**Issue by gugaua** [CardinalHorizon/VAOS#6]
Hello,

I am accessing http://vaos.gugaua.at/public/ and trying to "LOGIN" but all I get is

Not Found

The requested URL /public/login was not found on this server.

Is that expected?

**Comment by gugaua** [comment]
I had to enable rewrite mod in apache!

**Comment by BossOfGames** [comment]
I found it here. This is not expected behavior. How is this installed on the server. Is this on shared hosting?

http://vaos.gugaua.at/public/index.php/login

**Comment by gugaua** [comment]
okay,
http://vaos.gugaua.at/public/
Try to register and you will get

Not Found

The requested URL /register was not found on this server.

**Comment by BossOfGames** [comment]
Yep. Can you make sure your document root in you apache site config file is pointed to the public folder?

**Comment by gugaua** [comment]
ahh, everything looks much better now :)

If you need someone for testing, I can help

**Comment by BossOfGames** [comment]
Well... I mean... You kinda are :D
